server:
  port: 8549

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gpqh
    username: root
    password: 940415
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 4